### ISSUE TITLE
Stability Fund Stats: Add max cap per pool.

### ISSUE THREAD

**Issue by octocat512** [balancednetwork/balanced-network-info#114]
Personally, I want to know the max cap per pool.
![image](https://user-images.githubusercontent.com/50083174/173530252-db12d10c-a1a3-4ca0-8ab4-36f06c021e4f.png)

**Comment by parrot9design** [comment]
Let's add a new column to display the maximum limit:
<img width="1241" alt="Screen Shot 2022-06-15 at 8 10 59 PM" src="https://user-images.githubusercontent.com/63842577/173777089-1b14b091-ee4b-46bd-9214-7867aed3be4b.png">

As the Stability Fund will only hold stablecoins, let's remove the dollar values from every row except `Total`. We should also decrease the % change values to 14px to make them less prominent.

@hetfly assuming the image will be enough for you to work from, but let us know if you have any questions.

**Comment by hetfly** [comment]
@parrot9design just to be clear - in the `Total` row, there is `$` displayed but stable coin rates are not reflected. Because we show token amount in respective token rows, totals wouldn't add up correctly and if stability fund was near its cap, it could be showing something like `$4,555,000` in the fund out of max limit `$4,500,000`.

Is this alright?

**Comment by parrot9design** [comment]
I used the $ in the totals to keep it consistent with the totals in the other sections, but we should base it on the total amount of stablecoins rather than their actual rates, because they’re always treated as $1 in this scenario. So even if IUSDC and USDS are trading above $1 on the DEX and the Stability Fund is at the maximum limit, the total should never be above $4,500,000.
