### ISSUE TITLE
Update the Collateral and Loan sections to highlight the value backing bnUSD

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#116]
Maybe an entire page about bnUSD, maybe just a section, but after UST collapse, stablecoin backing and details are valued by users.

Some ideas:

- Total $$ value backing it
- breakdown of assets backing it (Stability fund + collateral)

**Comment by parrot9design** [comment]
Let's update the `Loan` section to be called `Balanced Dollars`, and give the Collateral section a dropdown menu:

<img width="1242" alt="Screen Shot 2022-08-26 at 1 40 03 PM" src="https://user-images.githubusercontent.com/63842577/187605194-c372bf55-d345-4265-8c48-17313277f42a.png">

![slice1](https://user-images.githubusercontent.com/63842577/187605232-cefe3bec-d0ef-4cf8-aa41-e0d1ed78c866.png)

---

The Collateral section should display a different set of values depending on which option is active:

<img width="611" alt="Screen Shot 2022-08-26 at 1 40 03 PM copy" src="https://user-images.githubusercontent.com/63842577/187605523-31a3d64f-5198-4a47-b5c6-49291089b7e5.png">

<img width="616" alt="Screen Shot 2022-08-26 at 1 44 40 PM copy" src="https://user-images.githubusercontent.com/63842577/187605365-45844901-670c-47ea-82ba-057b2d96aa34.png">

<img width="607" alt="Screen Shot 2022-08-26 at 1 55 46 PM" src="https://user-images.githubusercontent.com/63842577/187605385-4bc5a983-3bf8-4f4c-9b73-840d07198600.png">

<img width="608" alt="Screen Shot 2022-08-26 at 1 47 42 PM" src="https://user-images.githubusercontent.com/63842577/187605369-e7126f5e-5c29-4bc5-8279-7f25be2b9c47.png">
(all new collateral types will use the details used in this variation)

---
Notes:

- Have used ICX as the ticker for the ICON collateral type as people are more familiar with it, but happy to be challenged on this. Whichever one we choose, the ticker used for the Collateral section in the app should be consistent with this one.
  - If ICX, use `ICX price` as the middle value
  - If sICX, use `sICX / ICX price`

- Ignore the horizontal line on the Collateral charts

- We'll need to update the Y axis on the Collateral chart to use $ values, rather than number of tokens:
<img width="613" alt="Screen Shot 2022-08-31 at 6 10 31 PM" src="https://user-images.githubusercontent.com/63842577/187606575-7cf1b497-247b-48a5-9b73-21c2847bcc58.png">

- Don't think this is possible yet, but it'd be awesome if we could update the info on the Balanced Dollars chart based on which collateral type is currently active.

- Here's the icon for the Stability Fund. Will get the All icon for you soon.
[stability-fund.svg.zip](https://github.com/balancednetwork/balanced-network-info/files/9459038/stability-fund.svg.zip)

Let us know if you have any questions.
