### ISSUE TITLE
Add an anchor link to each section 

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-info#175]
It would be helpful if each section on the Stats & Performance Details pages included an anchor link to make it easy to send people to specific sections, e.g. the Stability Fund or withdrawal limits.

**Comment by hetfly** [comment]
@parrot9design 

since all of the data is loaded asynchronously, sometimes the anchors are not exact. Tried to prevent it but it's not very well possible all of the time. What I tried, though, seems pretty good.

https://stats.balanced.network/#savings-rate
https://stats.balanced.network/#tokens
https://stats.balanced.network/#exchange
https://stats.balanced.network/#enshrinement
https://stats.balanced.network/#governance
https://stats.balanced.network/#baln
https://stats.balanced.network/#holdings
https://stats.balanced.network/#withdrawal-limits
https://stats.balanced.network/performance-details#holdings-history
https://stats.balanced.network/performance-details#stability-fund
